Import Necessary Libraries

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd

In [3]:
import warnings
warnings.filterwarnings('ignore')

Import all datssets

In [4]:
#WD - Weekday , WE - Weekend
amsterdam_WD = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/amsterdam_weekdays.csv')
amsterdam_WE =  pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/amsterdam_weekends.csv')
athens_WD = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/athens_weekdays.csv')
athens_WE = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/athens_weekends.csv')
barcelona_WD = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/barcelona_weekdays.csv')
barcelona_WE = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/barcelona_weekends.csv')
berlin_WD = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/berlin_weekdays.csv')
berlin_WE = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/berlin_weekends.csv')
budapest_WD = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/budapest_weekdays.csv')
budapest_WE = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/budapest_weekends.csv')
lisbon_WD = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/lisbon_weekdays.csv')
lisbon_WE = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/lisbon_weekends.csv')
london_WD = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/london_weekdays.csv')
london_WE = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/london_weekends.csv')
paris_WD = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/paris_weekdays.csv')
paris_WE = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/paris_weekends.csv')
rome_WD = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/rome_weekdays.csv')
rome_WE = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/rome_weekends.csv')
vienna_WD = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/vienna_weekdays.csv')
vienna_WE = pd.read_csv('/content/drive/MyDrive/Masai/CWP_41/vienna_weekends.csv')

Checking the shape of all the datasets

In [5]:
print('amsterdam_WD = ',amsterdam_WD.shape)
print('amsterdam_WE = ',amsterdam_WE.shape)
print('athens_WD = ',athens_WD.shape)
print('athens_WE = ',athens_WE.shape)
print('barcelona_WD = ',barcelona_WD.shape)
print('barcelona_WE = ',barcelona_WE.shape)
print('berlin_WD = ',berlin_WD.shape)
print('berlin_WE = ',berlin_WE.shape)
print('budapest_WD = ',budapest_WD.shape)
print('budapest_WE = ',budapest_WE.shape)
print('lisbon_WD = ',lisbon_WD.shape)
print('lisbon_WE = ',lisbon_WE.shape)
print('london_WD = ',london_WD.shape)
print('london_WE = ',london_WE.shape)
print('paris_WD = ',paris_WD.shape)
print('paris_WE = ',paris_WE.shape)
print('rome_WD = ',rome_WD.shape)
print('rome_WE = ',rome_WE.shape)
print('vienna_WD = ',vienna_WD.shape)
print('vienna_WE = ',vienna_WE.shape)

amsterdam_WD =  (1103, 20)
amsterdam_WE =  (977, 20)
athens_WD =  (2653, 20)
athens_WE =  (2627, 20)
barcelona_WD =  (1555, 20)
barcelona_WE =  (1278, 20)
berlin_WD =  (1284, 20)
berlin_WE =  (1200, 20)
budapest_WD =  (2074, 20)
budapest_WE =  (1948, 20)
lisbon_WD =  (2857, 20)
lisbon_WE =  (2906, 20)
london_WD =  (4614, 20)
london_WE =  (5379, 20)
paris_WD =  (3130, 20)
paris_WE =  (3558, 20)
rome_WD =  (4492, 20)
rome_WE =  (4535, 20)
vienna_WD =  (1738, 20)
vienna_WE =  (1799, 20)

Checking the columns in the all the datasets

In [6]:
print(amsterdam_WD.columns)
print(amsterdam_WE.columns)
print(athens_WD.columns)
print(athens_WE.columns)
print(barcelona_WD.columns)
print(barcelona_WE.columns)
print(berlin_WD.columns)
print(berlin_WE.columns)
print(budapest_WD.columns)
print(budapest_WE.columns)
print(lisbon_WD.columns)
print(lisbon_WE.columns)
print(london_WD.columns)
print(london_WE.columns)
print(paris_WD.columns)
print(paris_WE.columns)
print(rome_WD.columns)
print(rome_WE.columns)
print(vienna_WD.columns)
print(vienna_WE.columns)

Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')
Index(['Unnamed: 0', 'realSum', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'multi', 'biz',
       'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist',
       'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index',
       'rest_index_norm', 'lng', 'lat'],
      dtype='object')

You can see all the columns in all the datasets is the same so we can concatenate all the dataset into one by creating separate columns for weekdays/weekend and cities.

In [7]:
 #creating a function to create two new columns for weekdays/weekend and cities and merging them.
def Combine_same_city(file1,WD,file2,WE,city):
    file1['week_type'] = WD
    file2['week_type'] = WE
    file1.drop(columns = ['Unnamed: 0'],inplace=True) #droping the unnecessary column in the dataset
    file2.drop(columns = ['Unnamed: 0'],inplace=True) ##droping the unnecessary column in the dataset
    combined = pd.concat([file1,file2])
    combined['city'] = city
    return combined

In [8]:
#combining dataset as per cities
amsterdam = Combine_same_city(amsterdam_WD,'weekday',amsterdam_WE,'weekend',"Amsterdam")
athens = Combine_same_city(athens_WD,'weekday',athens_WE,'weekend',"Athens")
barcelona = Combine_same_city(barcelona_WD,'weekday',barcelona_WE,'weekend',"Barcelona")
berlin = Combine_same_city(berlin_WD,'weekday',berlin_WE,'weekend',"Berlin")
budapest = Combine_same_city(budapest_WD,'weekday',budapest_WE,'weekend',"Budapest")
lisbon = Combine_same_city(lisbon_WD,'weekday',lisbon_WE,'weekend',"Lisbon")
london = Combine_same_city(london_WD,'weekday',london_WE,'weekend',"London")
paris = Combine_same_city(paris_WD,'weekday',paris_WE,'weekend',"Paris")
rome = Combine_same_city(rome_WD,'weekday',rome_WE,'weekend',"Rome")
vienna = Combine_same_city(vienna_WD,'weekday',vienna_WE,'weekend',"Vienna")

In [9]:
#taking all the city wise data into a list for concatination
city_data = [amsterdam,athens,barcelona,berlin,budapest,lisbon,london,paris,rome,vienna]

In [10]:
#Concatinating all the city wise data into a single file (appending all the rows )
europe_data = pd.concat(city_data, ignore_index = True)

In [11]:
europe_data.shape #checking the shape of the final dataset

(51707, 21)

In [12]:
europe_data.head() #checking the top 5 rows of the data

,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,week_type,city
0,194.033698,Private room,False,True,2.0,False,1,0,10.0,93.0,...,5.022964,2.539380,78.690379,4.166708,98.253896,6.846473,4.90569,52.41772,weekday,Amsterdam
1,344.245776,Private room,False,True,4.0,False,0,0,8.0,85.0,...,0.488389,0.239404,631.176378,33.421209,837.280757,58.342928,4.90005,52.37432,weekday,Amsterdam
2,264.101422,Private room,False,True,2.0,False,0,1,9.0,87.0,...,5.748312,3.651621,75.275877,3.985908,95.386955,6.646700,4.97512,52.36103,weekday,Amsterdam
3,433.529398,Private room,False,True,4.0,False,0,1,9.0,90.0,...,0.384862,0.439876,493.272534,26.119108,875.033098,60.973565,4.89417,52.37663,weekday,Amsterdam
4,485.552926,Private room,False,True,2.0,True,0,0,10.0,98.0,...,0.544738,0.318693,552.830324,29.272733,815.305740,56.811677,4.90051,52.37508,weekday,Amsterdam

In [13]:
#exporting the final dataset to a csv file
europe_data.to_csv('europe_data.csv')